### ISSUE TITLE
No Metrics found for measure set cpuUsage on ETL

### ISSUE THREAD

**Issue by jonathansampson** [MicrosoftEdge/BrowserEfficiencyTest#86] opened 2017-05-09 23:22 UTC
I believe I have followed all setup instructions correctly, however none of the cpuUsage data appears to be collected. Also, the generated CSV is empty:

**Command**
```
BrowserEfficiencyTest.exe -b edge chrome -i 2 -rp C:\Traces -ms cpuUsage -s FastScenario WikipediaUnitedStates
```

The tests opened the two browsers, and appeared to run successfully.

**Output**
```
Completed Test Pass
- Starting performance processing. -
- Processing ETL C:\Traces\chrome_fastscenario-wikipediaunitedstates_0_cpuUsage_20170509_172604.etl using profile .\MeasureSetDefinitionAssets\CpuUsage.wpaProfile
WPA 10.0.15063.137 (WinBuild.160101.0800)
No Metrics found for measure set cpuUsage on ETL C:\Traces\chrome_fastscenario-wikipediaunitedstates_0_cpuUsage_20170509_172604.etl.
- Processing ETL C:\Traces\chrome_fastscenario-wikipediaunitedstates_0_cpuUsage_20170509_172933.etl using profile .\MeasureSetDefinitionAssets\CpuUsage.wpaProfile
WPA 10.0.15063.137 (WinBuild.160101.0800)
No Metrics found for measure set cpuUsage on ETL C:\Traces\chrome_fastscenario-wikipediaunitedstates_0_cpuUsage_20170509_172933.etl.
- Processing ETL C:\Traces\chrome_fastscenario-wikipediaunitedstates_1_cpuUsage_20170509_173146.etl using profile .\MeasureSetDefinitionAssets\CpuUsage.wpaProfile
WPA 10.0.15063.137 (WinBuild.160101.0800)
No Metrics found for measure set cpuUsage on ETL C:\Traces\chrome_fastscenario-wikipediaunitedstates_1_cpuUsage_20170509_173146.etl.
- Processing ETL C:\Traces\edge_fastscenario-wikipediaunitedstates_0_cpuUsage_20170509_173038.etl using profile .\MeasureSetDefinitionAssets\CpuUsage.wpaProfile
WPA 10.0.15063.137 (WinBuild.160101.0800)
No Metrics found for measure set cpuUsage on ETL C:\Traces\edge_fastscenario-wikipediaunitedstates_0_cpuUsage_20170509_173038.etl.
- Processing ETL C:\Traces\edge_fastscenario-wikipediaunitedstates_1_cpuUsage_20170509_173251.etl using profile .\MeasureSetDefinitionAssets\CpuUsage.wpaProfile
WPA 10.0.15063.137 (WinBuild.160101.0800)
No Metrics found for measure set cpuUsage on ETL C:\Traces\edge_fastscenario-wikipediaunitedstates_1_cpuUsage_20170509_173251.etl.
```

**Generated CSV**
```
EtlFileName,Scenario,Iteration,Browser,DateStamp,TimeStamp,MeasureSet,Measure,Result

```

**Comment by TychosNose** [comment] 2017-05-16 18:26
Hi Jonathan, everything you show above looks correct. If Elevator wasn't running BET would throw an error and if the WPRP file did not contain a cpuUsage profile Elevator would throw an error and you wouldn't get any ETL files. The only thing I can think of is the WPA/WPR version you are using is one I have not tried. From the output above it looks like you have a Windows Insider version of WPA/WPR v10.0.15063.137. Can you try the publicly available version v14393 and see if that fixes this for you? I'll see if I can get a Windows Insider version of WPA/WPR and try to reproduce this.

**Comment by TychosNose** [comment] 2017-05-16 18:36
Here is a link to the Windows Performance Toolk kit page: https://msdn.microsoft.com/en-us/windows/hardware/commercialize/test/wpt/index

**Comment by TychosNose** [comment] 2017-05-16 18:50
I was able to recreate the issue using the latest insiders version of WPA. I'll see if I can figure out why it returns nothing for CPU metrics.

**Comment by jonathansampson** [comment] 2017-05-16 19:03
@TychosNose Thank you for the prompt feedback, and diligence in testing. I am not part of the Insiders Program, and am using the general release of 15063. Please let me know if there is anything further I can do to assist you in your efforts.

**Comment by TychosNose** [comment] 2017-05-16 20:33
Thanks for the info Jonathan. The issue is that WPAExporter throws an InvalidOperationException when attempting to export from the ETLs. I've tried re-exporting the profiles with the latest WPA but still no luck. I'll see if there is a known solution to this problem.

**Comment by TychosNose** [comment] 2017-05-17 01:46
@jonathansampson I believe I've got a fix for the CpuUsage metrics issue. Try using the updated CpuUsage.wpaProfile in PR #88 and see if that fixes the issue. I verified I was able to get CPU usage metrics with this profile using both WPAExporter v10.0.14393 and the latest Insider version v10.0.16190.1000 so I believe it will work for v15063 you have as well.

**Comment by TychosNose** [comment] 2017-05-23 03:03
@jonathansampson I've merged the fix for this into master. I will close this issue now. Please file more issues if you encounter other problems.

**Closed by TychosNose** 2017-05-23 03:03 UTC

**Comment by jonathansampson** [comment] 2017-05-24 00:37
Thanks, I'll revisit my project asap and see if this resolves the issue for me.
